# Generated by Django 4.0.3 on 2022-11-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('USN', models.CharField(default='', max_length=3)),
                ('clg_name', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
