# Generated by Django 4.0.3 on 2022-11-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
    ]
