# Generated by Django 4.0.3 on 2022-11-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_APP', '0002_rename_employee_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='intrests',
            field=models.ManyToManyField(to='Student_APP.intrest'),
        ),
    ]
